[package]
name = "tradingview_common"
version = "0.1.0"
edition = "2021"

[dependencies]
# json
miniserde = "0.1.40"
# error handling
simple_error = { git = "https://github.com/brandonros/simple_error.git" }
# logging
log = "0.4.22"
